# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Crosslife
tagline:          ''
description:      'Coding The World'
url:              http://www.geziyang.com

author:
  name:           'geziyang'
  url:            http://geziyang.com

paginate:         5