# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            waynehsu
tagline:          ''
description:      'day day study'
url:              http://www.kaoputive.com

author:
  name:           'waynehsu'
  url:            http://kaoputive.com

paginate:         5